var autolinkConfig = {

    'http://dom.spec.whatwg.org/': {
        'AT_TARGET': '#dom-event-at_target',
        'DATA_CLONE_ERR': '#dom-domexception-data_clone_err',
        'DOCUMENT_FRAGMENT_NODE': '#dom-node-document_fragment_node',
        'InvalidNodeTypeError': '#invalidnodetypeerror',
        'NodeList': '#nodelist',
        'ancestor': '#concept-tree-ancestor',
        'bubbles': '#dom-event-bubbles',
        'cloneNode()': '#dom-node-clonenode',
        'context object': '#context-object',
        'currentTarget': '#dom-event-currenttarget',
        'descendant': '#concept-tree-descendant',
        'document': '#concept-document',
        'document.getElementById': '#dom-document-getelementbyid',
        'document.getElementsByClassNameId': '#dom-document-getelementsbyclassname',
        'document.getElementsByTagName': '#dom-document-getelementsbytagname',
        'document.getElementsByTagNameNS': '#dom-document-getelementsbytagnamens',
        'element': '#concept-element',
        'event dispatch': '#concept-event-dispatch',
        'event listener invoke': '#concept-event-listener-invoke',
        'event listener': '#concept-event-listener',
        'event': '#events',
        'eventPhase': '#dom-event-eventphase',
        'inclusive ancestor': '#concept-tree-inclusive-ancestor',
        'interface Document': '#interface-document',
        'interface DocumentFragment': '#interface-documentfragment',
        'node tree': '#concept-node-tree',
        'node': '#concept-node',
        'nodeName': '#dom-node-nodename',
        'nodeType': '#dom-node-nodetype',
        'ownerDocument': '#dom-node-ownerdocument',
        'parent': '#concept-tree-parent',
        'participates': '#concept-tree-participate',
        'preceding': '#concept-tree-preceding',
        'range': '#range',
        'root': '#concept-tree-root',
        'static': '#concept-collection-static',
        'stop propagation flag': '#stop-propagation-flag',
        'target': '#dom-event-target',
        'tree order': '#concept-tree-order',
        'tree': '#trees'
    },

    'http://www.whatwg.org/specs/web-apps/current-work/multipage/': {
        'DOM tree accessors': 'dom.html#dom-tree-accessors',
        'Document object': 'dom.html#document',
        'HTML': '',
        'HTML elements': 'semantics.html#semantics',
        'HTML fragment serialization algorithm': 'the-end.html#html-fragment-serialization-algorithm',
        'activeElement': 'editing.html#dom-document-activeelement',
        'audio element': 'the-video-element.html#the-audio-element',
        'base element': 'semantics.html#the-base-element',
        'boolean': 'common-microsyntaxes.html#boolean-attribute',
        'canvas element': 'the-canvas-element.html#the-canvas-element',
        'comma separated tokens': 'common-microsyntaxes.html#comma-separated-tokens',
        'contenteditable': 'editing.html#attr-contenteditable',
        'details element': 'interactive-elements.html#the-details-element',
        'embed element': 'the-iframe-element.html#the-embed-element',
        'fallback content': 'elements.html#fallback-content',
        'fieldset element': 'forms.html#the-fieldset-element',
        'flow content': 'elements.html#flow-content-0',
        'focusable': 'editing.html#focusable',
        'form element': 'forms.html#the-form-element',
        'form submission': 'association-of-controls-and-forms.html#form-submission',
        'form-associated element': 'forms.html#form-associated-element',
        'forms': 'forms.html#forms',
        'iframe element': 'the-iframe-element.html#the-iframe-element',
        'img element': 'embedded-content-1.html#the-img-element',
        'input element': 'the-input-element.html#the-input-element',
        'link element': 'semantics.html#the-link-element',
        'map element': 'the-map-element.html#the-map-element',
        'meter element': 'the-button-element.html#the-meter-element',
        'named access on the window object': 'browsers.html#named-access-on-the-window-object',
        'object element': 'the-iframe-element.html#the-object-element',
        'progress element': 'the-button-element.html#the-progress-element',
        'reflect': 'common-dom-interfaces.html#reflect',
        'style': 'elements.html#the-style-attribute',
        'textarea element': 'the-button-element.html#the-textarea-element',
        'transparent': 'elements.html#transparent',
        'tree accessors': 'dom.html#dom-tree-accessors',
        'video element': 'the-video-element.html#the-video-element',
        'window': 'browsers.html#window'
    }
};
